#!/bin/bash
#PBS -V
#PBS -q q-1jour
#PBS -M h.leroy@epfl.ch
#PBS -m ae

#SBATCH --chdir /home/hcleroy/Line_Diagram
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem 4096
#SBATCH --time 12:30:00

#On se place dans le repertoire de travail
#cd /home/hleroy/Simulation/Line_Diagram/
#cd /home/hcleroy/Self_Fiber/Numerical_Computation/RandomParticle/Cluster/Line_Diagram

#cd $PBS_O_WORKDIR

#on lance le calcul
python3 Loop_For_High_L.py $1 $2 $3 $4
#python3 Loop.py $1
